# Generated by Django 3.0.3 on 2020-07-22 18:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grb_name', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('ra', models.FloatField(blank=True, help_text='Right Ascension, in degrees.', null=True, verbose_name='Right Ascension')),
                ('dec', models.FloatField(blank=True, help_text='Declination, in degrees.', null=True, verbose_name='Declination')),
            ],
        ),
    ]
