# Generated by Django 3.0.3 on 2020-07-22 19:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grb',
            name='AV',
            field=models.FloatField(blank=True, help_text='AV, in degrees.', null=True, verbose_name='AV'),
        ),
        migrations.AddField(
            model_name='grb',
            name='SFR',
            field=models.FloatField(blank=True, help_text='SFR, in degrees.', null=True, verbose_name='SFR'),
        ),
        migrations.AddField(
            model_name='grb',
            name='Z_gas',
            field=models.FloatField(blank=True, help_text='Gas Metallicity, in degrees.', null=True, verbose_name='Gas Metallicity'),
        ),
        migrations.AddField(
            model_name='grb',
            name='Z_stellar',
            field=models.FloatField(blank=True, help_text='Metallicity, in degrees.', null=True, verbose_name='Metallicity'),
        ),
        migrations.AddField(
            model_name='grb',
            name='age',
            field=models.FloatField(blank=True, help_text='Age, in degrees.', null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='grb',
            name='mass',
            field=models.FloatField(blank=True, help_text='Mass, in degrees.', null=True, verbose_name='Mass'),
        ),
        migrations.AddField(
            model_name='grb',
            name='tau',
            field=models.FloatField(blank=True, help_text='TAU, in degrees.', null=True, verbose_name='TAU'),
        ),
        migrations.AddField(
            model_name='grb',
            name='z',
            field=models.FloatField(blank=True, help_text='Red Shift, in degrees.', null=True, verbose_name='Red Shift'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Additional info about the GRB that may be of note'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='grb_name',
            field=models.CharField(help_text='Name of GRB', max_length=200),
        ),
    ]
