# Generated by Django 3.0.3 on 2020-07-29 16:14

import django.contrib.postgres.fields
from django.db import migrations, models
import grbs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0003_grb_spectrogram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grb',
            old_name='description',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='SFR',
            new_name='sfr',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='AV',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='Z_gas',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='Z_stellar',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='tau',
        ),
        migrations.AddField(
            model_name='grb',
            name='dust1',
            field=models.FloatField(blank=True, help_text='dust1.', null=True, verbose_name='dust1'),
        ),
        migrations.AddField(
            model_name='grb',
            name='dust2',
            field=models.FloatField(blank=True, help_text='dust2.', null=True, verbose_name='dust2'),
        ),
        migrations.AddField(
            model_name='grb',
            name='filters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['sdss_g0', 'sdss_r0', 'sdss_i0', 'sdss_z0', 'fourstar_j'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grb',
            name='gas_logu',
            field=models.FloatField(blank=True, help_text='Log Gas ??.', null=True, verbose_name='Log Gas ??'),
        ),
        migrations.AddField(
            model_name='grb',
            name='gas_logz',
            field=models.FloatField(blank=True, help_text='Log Gas Metallicity.', null=True, verbose_name='Log Gas Metallicity'),
        ),
        migrations.AddField(
            model_name='grb',
            name='logzsol',
            field=models.FloatField(blank=True, help_text='Log Solar Metallicity.', null=True, verbose_name='Log Solar Metallicity'),
        ),
        migrations.AddField(
            model_name='grb',
            name='phot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[25.435, 25.435, 25.435, 25.435], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grb',
            name='phot_error',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.08, 0.08, 0.08, 0.08], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grb',
            name='samples',
            field=models.FileField(default=None, null=True, upload_to='samples/', validators=[grbs.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='grb',
            name='t_90',
            field=models.FloatField(blank=True, help_text='??', null=True, verbose_name='Red Shift'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='age',
            field=models.FloatField(blank=True, help_text='Age', null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='mass',
            field=models.FloatField(blank=True, help_text='Mass', null=True, verbose_name='Mass'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='spectrogram',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[grbs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='grb',
            name='z',
            field=models.FloatField(blank=True, help_text='Red Shift', null=True, verbose_name='Red Shift'),
        ),
    ]
