# Generated by Django 3.0.3 on 2020-07-29 21:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0004_auto_20200729_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grb',
            old_name='phot_error',
            new_name='phot_err_lower',
        ),
        migrations.AddField(
            model_name='grb',
            name='age_err_lower',
            field=models.FloatField(blank=True, help_text='Age Lower Error', null=True, verbose_name='Age Lower Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='age_err_upper',
            field=models.FloatField(blank=True, help_text='Age Upper Error', null=True, verbose_name='Age Upper Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='dust1_err_lower',
            field=models.FloatField(blank=True, help_text='Dust1 Lower Error', null=True, verbose_name='Dust1 Lower Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='dust1_err_upper',
            field=models.FloatField(blank=True, help_text='Dust1 Upper Error', null=True, verbose_name='Dust1 Upper Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='dust2_err_lower',
            field=models.FloatField(blank=True, help_text='Dust2 Lower Error', null=True, verbose_name='Dust2 Lower Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='dust2_err_upper',
            field=models.FloatField(blank=True, help_text='Dust2 Upper Error', null=True, verbose_name='Dust2 Upper Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='logzsol_err_lower',
            field=models.FloatField(blank=True, help_text='Log Solar Metallicity Lower Error', null=True, verbose_name='Log Solar Metallicity Lower Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='logzsol_err_upper',
            field=models.FloatField(blank=True, help_text='Log Solar Metallicity Upper Error', null=True, verbose_name='Log Solar Metallicity Upper Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='mass_err_lower',
            field=models.FloatField(blank=True, help_text='Mass Lower Error', null=True, verbose_name='Mass Lower Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='mass_err_upper',
            field=models.FloatField(blank=True, help_text='Mass Upper Error', null=True, verbose_name='Mass Upper Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='phot_err_upper',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[-0.228, -0.187, -0.189, -0.216, -0.236, -0.225, -0.189, -0.23, -0.462], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grb',
            name='sfr_err_lower',
            field=models.FloatField(blank=True, help_text='Star Formation Rate Lower Error', null=True, verbose_name='Star Formation Rate Lower Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='sfr_err_upper',
            field=models.FloatField(blank=True, help_text='Star Formation Rate Upper Error', null=True, verbose_name='Star Formation Rate Upper Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='z_err_lower',
            field=models.FloatField(blank=True, help_text='Red Shift Lower Error', null=True, verbose_name='Red Shift Lower Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='z_err_upper',
            field=models.FloatField(blank=True, help_text='Red Shift Upper Error', null=True, verbose_name='Red Shift Upper Error'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='dec',
            field=models.FloatField(blank=True, help_text='Declination, in degrees.', max_length=20, null=True, verbose_name='Declination'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='ra',
            field=models.CharField(blank=True, help_text='Right Ascension, in degrees.', max_length=20, null=True, verbose_name='Right Ascension'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='sfr',
            field=models.FloatField(blank=True, help_text='Star Formation Rate.', null=True, verbose_name='Star Formation Rate'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='t_90',
            field=models.FloatField(blank=True, help_text='??', null=True, verbose_name='T 90'),
        ),
    ]
