# Generated by Django 3.0.3 on 2020-07-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0005_auto_20200729_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grb',
            name='dec',
            field=models.CharField(blank=True, help_text='Declination, in degrees.', max_length=20, null=True, verbose_name='Declination'),
        ),
    ]
