# Generated by Django 3.0.3 on 2020-08-04 14:04

import django.contrib.postgres.fields
from django.db import migrations, models
import grbs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0006_auto_20200729_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grb',
            old_name='spectrogram',
            new_name='cornerplot',
        ),
        migrations.AddField(
            model_name='grb',
            name='sed',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[grbs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='grb',
            name='filters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='grb',
            name='phot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='grb',
            name='phot_err_lower',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='grb',
            name='phot_err_upper',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), size=None),
        ),
    ]
