# Generated by Django 3.0.3 on 2020-08-04 14:09

import django.contrib.postgres.fields
from django.db import migrations, models
import grbs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0007_auto_20200804_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grb',
            name='filters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='grb',
            name='phot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='grb',
            name='phot_err_lower',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='grb',
            name='phot_err_upper',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='grb',
            name='samples',
            field=models.FileField(blank=True, null=True, upload_to='samples/', validators=[grbs.validators.validate_file_extension]),
        ),
    ]
