# Generated by Django 3.0.3 on 2020-08-04 15:03

from django.db import migrations, models
import grbs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0009_auto_20200804_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='grb',
            name='json_metadata',
            field=models.FileField(blank=True, null=True, upload_to='json/', validators=[grbs.validators.validate_file_extension]),
        ),
    ]
