# Generated by Django 3.0.3 on 2020-08-04 15:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0010_grb_json_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='grb',
            name='phot_reference',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='grb',
            name='phot_source',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='grb',
            name='sky_location_reference',
            field=models.CharField(blank=True, help_text='Reference for sky location information.', max_length=20, null=True, verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='grb',
            name='sky_location_source',
            field=models.CharField(blank=True, help_text='Telescope from which sky location is derived', max_length=20, null=True, verbose_name='Telescope Name'),
        ),
    ]
