# Generated by Django 3.0.3 on 2020-08-05 17:47

import django.contrib.postgres.fields
from django.db import migrations, models
import grbs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0011_auto_20200804_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grb',
            old_name='cornerplot',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='samples',
            new_name='h5',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='phot_err_lower',
            new_name='phot_err',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='phot_reference',
            new_name='phot_refs',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='phot_err_upper',
            new_name='phot_wave',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='phot_source',
            new_name='spec_ref',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='dec',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='gas_logz',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='ra',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='sky_location_reference',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='sky_location_source',
        ),
        migrations.AddField(
            model_name='grb',
            name='corner',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[grbs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='grb',
            name='dec_host',
            field=models.CharField(blank=True, help_text='Declination, in degrees.', max_length=20, null=True, verbose_name='Declination of Host'),
        ),
        migrations.AddField(
            model_name='grb',
            name='fits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, null=True, upload_to='samples/', validators=[grbs.validators.validate_file_extension]), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='grb',
            name='fluence',
            field=models.FloatField(blank=True, help_text='??', null=True, verbose_name='T 90'),
        ),
        migrations.AddField(
            model_name='grb',
            name='fluence_err_lower',
            field=models.FloatField(blank=True, help_text='??', null=True, verbose_name='T 90'),
        ),
        migrations.AddField(
            model_name='grb',
            name='fluence_err_upper',
            field=models.FloatField(blank=True, help_text='??', null=True, verbose_name='T 90'),
        ),
        migrations.AddField(
            model_name='grb',
            name='host_morphology',
            field=models.CharField(blank=True, help_text='Host galaxy Morphology.', max_length=20, null=True, verbose_name='Host Galaxy Morphology'),
        ),
        migrations.AddField(
            model_name='grb',
            name='host_sf',
            field=models.CharField(blank=True, help_text='Host Galaxy Star Formation.', max_length=20, null=True, verbose_name='Host Galaxy Star Formation'),
        ),
        migrations.AddField(
            model_name='grb',
            name='offset',
            field=models.FloatField(blank=True, help_text='Offset', null=True, verbose_name='Offset'),
        ),
        migrations.AddField(
            model_name='grb',
            name='offset_err_lower',
            field=models.FloatField(blank=True, help_text='Offset Lower Error', null=True, verbose_name='Offset Lower Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='offset_err_upper',
            field=models.FloatField(blank=True, help_text='Offset Upper Error', null=True, verbose_name='Offset Upper Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='offset_kpc',
            field=models.FloatField(blank=True, help_text='Offset in KPC', null=True, verbose_name='Offset KPC'),
        ),
        migrations.AddField(
            model_name='grb',
            name='offset_kpc_err_lower',
            field=models.FloatField(blank=True, help_text='Offset KPC Lower Error', null=True, verbose_name='Offset KPC Lower Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='offset_kpc_err_upper',
            field=models.FloatField(blank=True, help_text='Offset KPC Upper Error', null=True, verbose_name='Offset KPC Upper Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='opt',
            field=models.CharField(blank=True, help_text='Reference for sky location information.', max_length=3, null=True, verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='grb',
            name='ra_host',
            field=models.CharField(blank=True, help_text='Right Ascension, in degrees.', max_length=20, null=True, verbose_name='Right Ascension of Host'),
        ),
        migrations.AddField(
            model_name='grb',
            name='radio',
            field=models.CharField(blank=True, help_text='Reference for sky location information.', max_length=3, null=True, verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='grb',
            name='spec_tel',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='grb',
            name='t_90_err_lower',
            field=models.FloatField(blank=True, help_text='??', null=True, verbose_name='T 90'),
        ),
        migrations.AddField(
            model_name='grb',
            name='t_90_err_upper',
            field=models.FloatField(blank=True, help_text='??', null=True, verbose_name='T 90'),
        ),
        migrations.AddField(
            model_name='grb',
            name='tel_pos',
            field=models.CharField(blank=True, help_text='Telescope from which sky location is derived', max_length=20, null=True, verbose_name='Telescope Position'),
        ),
        migrations.AddField(
            model_name='grb',
            name='tel_pos_ref',
            field=models.CharField(blank=True, help_text='Reference for sky location information.', max_length=20, null=True, verbose_name='Telescope Reference'),
        ),
        migrations.AddField(
            model_name='grb',
            name='telescopes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='grb',
            name='xray',
            field=models.CharField(blank=True, help_text='Reference for sky location information.', max_length=3, null=True, verbose_name='Reference'),
        ),
    ]
