# Generated by Django 3.0.3 on 2020-08-05 17:56

from django.db import migrations, models
import django.db.models.deletion
import grbs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0012_auto_20200805_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grb',
            name='fits',
        ),
        migrations.CreateModel(
            name='Fits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fits', models.FileField(blank=True, null=True, upload_to='fits/', validators=[grbs.validators.validate_file_extension])),
                ('grb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grbs.GRB')),
            ],
        ),
    ]
