# Generated by Django 3.0.3 on 2020-08-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0013_auto_20200805_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grb',
            old_name='t_90',
            new_name='t90',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='t_90_err_lower',
            new_name='t90_err_lower',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='t_90_err_upper',
            new_name='t90_err_upper',
        ),
        migrations.AlterField(
            model_name='grb',
            name='fluence',
            field=models.FloatField(blank=True, help_text='??', null=True, verbose_name='Fluence'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='fluence_err_lower',
            field=models.FloatField(blank=True, help_text='??', null=True, verbose_name='Fluence Lower Error'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='fluence_err_upper',
            field=models.FloatField(blank=True, help_text='??', null=True, verbose_name='Fluence Upper Error'),
        ),
    ]
