# Generated by Django 3.0.3 on 2020-08-05 20:38

import django.contrib.postgres.fields
from django.db import migrations, models
import grbs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0014_auto_20200805_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grb',
            name='gas_logu',
        ),
        migrations.AddField(
            model_name='grb',
            name='gas_logz',
            field=models.FloatField(blank=True, help_text='Gas Log Solar Metallicity.', null=True, verbose_name='Gas Log Solar Metallicity'),
        ),
        migrations.AddField(
            model_name='grb',
            name='gas_logz_err_lower',
            field=models.FloatField(blank=True, help_text='Gas Log Solar Metallicity Lower Error', null=True, verbose_name='Gas Log Solar Metallicity Lower Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='gas_logz_err_upper',
            field=models.FloatField(blank=True, help_text='Gas Log Solar Metallicity Upper Error', null=True, verbose_name='Gas Log Solar Metallicity Upper Error'),
        ),
        migrations.AddField(
            model_name='grb',
            name='mod_phot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='grb',
            name='mod_spec',
            field=models.FileField(blank=True, null=True, upload_to='model_spectrum/', validators=[grbs.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='grb',
            name='spec',
            field=models.FileField(blank=True, null=True, upload_to='observed_spectrum/', validators=[grbs.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='grb',
            name='z_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
