# Generated by Django 3.0.3 on 2020-08-11 19:24

from django.db import migrations, models
import grbs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0015_auto_20200805_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grb',
            name='mod_phot',
            field=models.FileField(blank=True, null=True, upload_to='model_phot/', validators=[grbs.validators.validate_file_extension]),
        ),
    ]
