# Generated by Django 3.0.3 on 2020-09-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0016_auto_20200811_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grb',
            name='spec_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grb',
            name='spec_tel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
