# Generated by Django 3.0.3 on 2020-09-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0017_auto_20200915_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorthand', models.CharField(blank=True, help_text='Citation short hand', max_length=100, null=True, verbose_name='Citation short hand')),
                ('url', models.URLField(blank=True, help_text='URL for reference', max_length=300, null=True, verbose_name='URL for reference')),
                ('grb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grbs.GRB')),
            ],
        ),
    ]
