# Generated by Django 3.0.3 on 2020-11-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0018_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='grb',
            name='gcn',
            field=models.URLField(blank=True, help_text='URL for GCN', max_length=300, null=True, verbose_name='URL for GCN'),
        ),
    ]
