# Generated by Django 3.0.3 on 2020-12-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0019_grb_gcn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grb',
            name='dec_host',
            field=models.CharField(blank=True, help_text='Declination, in degrees.', max_length=100, null=True, verbose_name='Declination of Host'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='grb_name',
            field=models.CharField(help_text='Name of GRB', max_length=1000),
        ),
        migrations.AlterField(
            model_name='grb',
            name='host_morphology',
            field=models.CharField(blank=True, help_text='Host galaxy Morphology.', max_length=100, null=True, verbose_name='Host Galaxy Morphology'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='host_sf',
            field=models.CharField(blank=True, help_text='Host Galaxy Star Formation.', max_length=100, null=True, verbose_name='Host Galaxy Star Formation'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='ra_host',
            field=models.CharField(blank=True, help_text='Right Ascension, in degrees.', max_length=100, null=True, verbose_name='Right Ascension of Host'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='tel_pos',
            field=models.CharField(blank=True, help_text='Telescope from which sky location is derived', max_length=100, null=True, verbose_name='Telescope Position'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='tel_pos_ref',
            field=models.CharField(blank=True, help_text='Reference for sky location information.', max_length=100, null=True, verbose_name='Telescope Reference'),
        ),
    ]
