# Generated by Django 3.0.3 on 2021-02-12 20:24

from django.db import migrations, models
import grbs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0021_grb_pcc'),
    ]

    operations = [
        migrations.AddField(
            model_name='grb',
            name='afterglow',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[grbs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='grb',
            name='frac_flux',
            field=models.FloatField(blank=True, help_text='frac_flux.', null=True, verbose_name='frac_flux'),
        ),
        migrations.AddField(
            model_name='grb',
            name='halflightrad',
            field=models.FloatField(blank=True, help_text='halflightrad', null=True, verbose_name='halflightrad'),
        ),
        migrations.AddField(
            model_name='grb',
            name='hnorm_offset',
            field=models.FloatField(blank=True, help_text='hnorm_offset', null=True, verbose_name='hnorm_offset'),
        ),
        migrations.AddField(
            model_name='grb',
            name='type_grb',
            field=models.CharField(choices=[('short', 'short'), ('long', 'long')], default='short', max_length=20),
            preserve_default=False,
        ),
    ]
