# Generated by Django 3.0.3 on 2021-02-12 20:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grbs', '0022_auto_20210212_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grb',
            name='comments',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Additional info about the GRB that may be of note', null=True),
        ),
    ]
